### ISSUE TITLE
Sketch doesn't work with original Digistump

### ISSUE THREAD

**Issue by labomat** [ArminJo/Arduino-OpenWindowAlarm#2]
I tried to use the sketch with the original Digistump board I got from the original kickstarter campaign - doesn't work. It uploads sucessfully but doesn't blink and doesn't sound the speaker.  I also got one of the chinese clones (red power led instead of green) - with this one it worked flawlessly ...

**Comment by ArminJo** [comment]
Thanks for reporting! Can not imagine the reason, maybe the board is defect or it is one of the boards I heard of, where the LED is connected different.

**Comment by labomat** [comment]
No, I don't think the board is broken. I tried with three boards: 2 from original Kickstarter one chinese clone. Both original boards didn't execute the windowalarm sketch but but the blink sketch (so I know the led is working). Maybe a different firmware?

**Comment by ArminJo** [comment]
What is the number of the LED in your blink sketch?

**Comment by labomat** [comment]
I was using LED_BUILTIN . I don't think its the led because the test sound at start didn't execute too.

**Comment by ArminJo** [comment]
Interesting, what happens if you change Line 167 `#define LED_PIN  PB1` to the pin where your led is connected?
And did you select 1 MHz as board frequency?

**Comment by labomat** [comment]
Ok, I got some more information. 
It seems the internal led on my board is connected to pin 0.
It seems I got a version where the led is interfering with i2c https://digistump.com/wiki/digispark/tutorials/modelbi2c
When I use pin 0 at line 167 I got an compile error "#error LED pin must not be equal TX pin."

**Comment by labomat** [comment]
Vielleicht auch noch interessant für Dich:
"Revision 3 ist laut Digistump eine Fälschung, die man deswegen eigentlich nicht kaufen sollte, auch wenn sie prinzipiell funktioniert. Andererseits ist die Revision 3 so weit verbreitet, dass man kaum eine andere bekommt. Und so habe ich selbst auch diese Version gekauft. Sie hat nur einen Nachteil: P5 ist bei diesem Modell als Reset Pin konfiguriert und deshalb nicht ohne Weiteres als I/O Pin nutzbar. Probiert es mal aus, wenn ihr einen „rev3“ habt. Startet einen Sketch und legt P5 kurz an GND – der Digispark startet neu. Entsprechend wird auch der Blink Sketch weiter unten mit P5 nicht funktionieren. Im letzten Abschitt des Beitrages erkläre ich wie man den Mangel beheben kann und den P5 zum I/O Pin macht. 

Um die Verwirrung komplett zu machen, gibt es auch Versionen ohne Revisionsnummer, die nicht original von Digistump stammen. Auch so ein Vertreter ist mir untergekommen und er funktionierte wie „rev3“. " (https://wolles-elektronikkiste.de/digispark-die-bequeme-attiny85-alternative)

**Comment by ArminJo** [comment]
Danke!
For Info: P5 as reset is highly recommended, as you have the possibility to burn a new bootloader if the old one does not work.
Revision 1 und 2 werden eigentlich von keiner aktuellen Software unterstützt, da sie nicht mehr zu kaufen und testen sind.

> When I use pin 0 at line 167 I got an compile error "#error LED pin must not be equal TX pin."

Disable the #define DEBUG etc. to avoid the error.
